### ISSUE TITLE
Option to disable need of authentification

### ISSUE THREAD

**Issue by Atem18** [coreos/registry-monitor#14]
Hi @josephschorr , is it possible to disable username and password for this script ?

Because not every private registry is protected by username / password.

Thanks in advance.

**Comment by josephschorr** [comment]
@Atem18 Can you give an example of a private registry that is not protected by a username/password, and where sending a fake pair would break?

**Comment by Atem18** [comment]
@josephschorr With sending a fake pair, it does work. Sorry for the disturbing.
