### ISSUE TITLE
registry-monitor is trying to pull from registry-1.docker.io instead of configured registry

### ISSUE THREAD

**Issue by iancward** [coreos/registry-monitor#15]
Hello there, 
I took this image and built it using Docker CE 17.12 and when I try to run the image locally and point it to my Quay Enterprise deployment, it seems to be trying to pull from registry-1.docker.io instead of the registry I told it to.

Here's how I'm running it:
```
docker run --privileged -e UNDER_DOCKER=true -v /var/run/docker.sock:/var/run/docker.sock -p 8000:8000 my.quay.install.com/utility/registry_monitor:20180206 -username=utility+registry_monitor -password=<robot password> -registry-host=my.quay.install.com -repository=registry_monitor_target -base-layer-id=<sha256 hash of :latest>
```

So I've built the code here and put it in a repo called `registry-monitor` and then I built a separate Alpine-based image that installs MySQL and stuff a string into /tmp/welcome (just to have something in the image).

Here's the output:
```
time="2018-02-08T20:50:48Z" level=info msg="Listening on :8000"
time="2018-02-08T20:50:48Z" level=info msg="Starting test"
time="2018-02-08T20:50:48Z" level=info msg="Trying to connect to Docker client"
time="2018-02-08T20:50:48Z" level=info msg="Docker client valid"
time="2018-02-08T20:50:48Z" level=info msg="Trying to connect to Docker client"
time="2018-02-08T20:50:48Z" level=info msg="Docker client valid"
time="2018-02-08T20:50:48Z" level=info msg="Clearing all images"
time="2018-02-08T20:50:48Z" level=info msg="Listing docker images"
time="2018-02-08T20:50:48Z" level=info msg="Clearing image sha256:<sha hash which is not even in the repo or a layer>"
time="2018-02-08T20:50:48Z" level=warning msg="Skipping deleting image sha256:<same sha hash as above>"
time="2018-02-08T20:50:48Z" level=info msg="Pulling test image"
time="2018-02-08T20:50:49Z" level=error msg="Pull Error: API error (500): {\"message\":\"Get https://registry-1.docker.io/v2/library/registry_monitor_target/manifests/latest: unauthorized: incorrect username or password\"}\n"
time="2018-02-08T20:50:49Z" level=info msg="Sleeping for 30s"
```

**Comment by iancward** [comment]
Is the expectation that this tool will pull an image from the public docker hub and push it to the registry defined in the CLI arguments? 
The pushTestImage function [makes use of](https://github.com/coreos/registry-monitor/blob/master/monitor.go#L387) the `registryHost` variable; however, the pullBaseImage function [doesn't specify the registry host at all](https://github.com/coreos/registry-monitor/blob/master/monitor.go#L284-L288), while the pullTestImage function [uses a hard-coded value of quay.io](https://github.com/coreos/registry-monitor/blob/master/monitor.go#L262-267)

**Comment by josephschorr** [comment]
Nope; its to be pushed and pulled from the same internal registry. If the registryHost doesn't correct specify, it should be changed. However, Docker 17-12 did cause a number of issues around registryHost, so its possible it is the first version that manifests the bug.

**Comment by iancward** [comment]
I downgraded to Docker engine to version `17.09.1~ce-0~ubuntu` and I'm still getting the same error.

**Comment by iancward** [comment]
I've also tried `17.03.2~ce-0~ubuntu-xenial` and `17.06.2~ce-0~ubuntu` versions and experienced the same error.

**Comment by iancward** [comment]
Ah, I think I figured it out. When you specify a `-repository` parameter, you need to need to use the full `registry/org/repo` path. The examples provided in the README seem to indicate this is how it should be used, so I'm not quite sure why I missed it.

It looks like now I just need to figure out why it can't create a new image:
```
time="2018-02-15T16:05:44Z" level=info msg="Status: Downloaded newer image for my.quay.install.com/utility/registry_monitor_target:latest\n"
time="2018-02-15T16:05:44Z" level=info msg="Deleting top layer"
time="2018-02-15T16:05:44Z" level=info msg="Creating new top layer"
time="2018-02-15T16:05:44Z" level=info msg="Creating new image via container updatedcontainer1518710744"
time="2018-02-15T16:05:44Z" level=error msg="Error creating container: no such image"
```

**Comment by iancward** [comment]
Ok it looks like this was caused by trying to use the hash that's in the URL of the repo ID in Quay. I went back to actually using the docker image ID from `docker images` and it appears to work.

**Comment by iancward** [comment]
Hmm, well if I use the Docker v1 image ID that corresponds to the `latest` tag in the repository as the value for `-base-layer-id`, I get one successful run and then on the next run, I see this:
```
time="2018-02-21T15:45:02Z" level=info msg="Deleting top layer"
time="2018-02-21T15:45:02Z" level=info msg="Creating new top layer"
time="2018-02-21T15:45:02Z" level=info msg="Creating new image via container updatedcontainer1519227902"
time="2018-02-21T15:45:02Z" level=error msg="Error creating container: no such image"
```

**Comment by iancward** [comment]
FYI I believe I got this working by using the `sha256:<foo>` ID instead of the Docker V1 ID.
The [ImageHistory](https://github.com/iancward/registry-monitor/blob/master/monitor.go#L459) function returns IDs of the format `sha256:<foo>` instead of Docker V1 IDs so I just use the whole thing for the parameter and it appears to be working.
